# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librapp.Author')),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librapp.Book')),
            ],
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_copies', models.IntegerField(default=0)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librapp.Book')),
            ],
        ),
        migrations.CreateModel(
            name='BookLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_out', models.DateTimeField(null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('date_in', models.DateTimeField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librapp.BookCopy')),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('card_no', models.IntegerField(primary_key=True, serialize=False)),
                ('ssn', models.CharField(max_length=9)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_amt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paid', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librapp.BookLoan')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bookloan',
            name='card_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librapp.Borrower'),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='lib_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librapp.LibraryBranch'),
        ),
    ]
