# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.URLField(default='no cover'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrower',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
