# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librapp', '0002_auto_20160705_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
