# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-09 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librapp', '0004_auto_20160709_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='card_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
